version: '3'

services:
    db:
        image: postgres
        volumes:
            - ./postgres:/docker-entrypoint-initdb.d/
            - ./data/postgres:/var/lib/postgresql/data
    gitea:
        image: gitea/gitea
        volumes:
            - ./data/gitea:/data
        ports:
            - "10022:22"
            - "8000:3000"
        depends_on: 
            - db
    jenkins:
        image: jenkins
        ports:
            - "8001:8080"
            - "50000:50000"
        volumes:
            - ./data/jenkins:/var/jenkins_home
    sonar:
        build:
            context: ./sonar
        ports:
            - "8002:9000"
            - "9092:9092"
        environment:
            - SONARQUBE_JDBC_USERNAME=sonar
            - SONARQUBE_JDBC_PASSWORD=sonar
            - SONARQUBE_JDBC_URL=jdbc:postgresql://db/sonar
        depends_on: 
            - db
    minio:
        image: minio/minio
        volumes:
            - ./data/minio/data:/data \
            - ./data/minio/config:/root/.minio \
        environment:
            - MINIO_ACCESS_KEY=MINIO_KEY
            - MINIO_SECRET_KEY=minio_secret_key
        ports:
            - "8003:9000"
        command: server /data