version: "3"

volumes:
  pg_data:
  gitea:
  drone:

services:
  db:
    image: postgres:alpine
    environment:
      - POSTGRES_USER=gitea
      - POSTGRES_PASSWORD=gitea
      - POSTGRES_DB=gitea
    volumes:
      - pg_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
  gitea:
    image: gitea/gitea
    environment:
      - USER_UID=1000
      - USER_GID=1001
      - DB_TYPE=postgres
      - DB_HOST=db:5432
      - DB_NAME=gitea
      - DB_USER=gitea
      - DB_PASSWD=gitea
      - ROOT_URL=http://${DC_HOST}:3000
    # restart: always
    volumes:
      - gitea:/data
    ports:
      - "3000:3000"
      - "20022:22"

  drone:
    image: drone/drone:1 
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - drone:/data
    environment:
      - DRONE_GITEA_SERVER=http://${DC_HOST}:3000
      - DRONE_GIT_ALWAYS_AUTH=true
      - DRONE_RUNNER_CAPACITY=2
      - DRONE_SERVER_HOST=${DC_HOST}
      - DRONE_SERVER_PROTO=http
      - DRONE_TLS_AUTOCERT=false
    ports:
      - "80:80"
      - "443:443"
    depends_on: 
      - gitea

  registry:
    image: registry:2
    ports:
      - "5000:5000"
  registry-ui:
    image: joxit/docker-registry-ui:static
    environment:
      - REGISTRY_URL=http://registry:5000
    ports:
      - "8000:80"
    
